import transmissionData from './TransmissionData';
import {kebbi, jebbaGs, ayade, olorunsogoNippGs, olorunsogoPhase1Gs, ajah, alagbon, egbinGs, fakun, ganmo, ikejaWest, ikorodu, odogunyan,
        jebba, kainji, kainjiGs, okearo, oshogbo, parasEnergyGs, sagamu, sakete, shiroroGs, lekki, katampe, ihovborNippGs, azuraIppGs,
        omotoshoNippGs, omotoshoPhase1Gs, akangba, kaduna, kano, dadinKowaGs, gombe, jos, markudi, gwagwalada, lokoja, benin, deltaGs,
        sapeleGs, aladja, sapeleNippGs, biu, damaturu, molai, ajaokuta, gereguGs, yola, gereguNipp, asaba, alaojiGs, owerri, ahaoda,
        transamadiGs, phMain, omokuGs, gbarainGs, riversIppGs, ugwuaji, newHaven, onitsha, alaoji, aba, yenegoa, afamIv_vGs, afamViGs,
        itu, adiabor, eket, ibomGs, ikotAbasi, ikotEkpene, odukpaniGs, okpaiGs
        } from './stations/index';

export var stations = [
    kebbi,
    jebbaGs,
    ayade,
    olorunsogoNippGs,
    olorunsogoPhase1Gs,
    sakete,
    ikejaWest,
    okearo,
    ajah,
    alagbon,
    lekki,
    egbinGs,
    ikorodu,
    odogunyan,
    sagamu,
    parasEnergyGs,
    fakun,
    kainji,
    kainjiGs,
    jebba,
    oshogbo,
    shiroroGs,
    ganmo,
    katampe,
    ihovborNippGs,
    azuraIppGs,
    omotoshoNippGs,
    omotoshoPhase1Gs,
    akangba,
    kaduna,
    kano,
    dadinKowaGs,
    jos,
    gombe,
    markudi,
    gwagwalada,
    lokoja,
    benin,
    deltaGs,
    sapeleGs,
    aladja,
    // sapeleNippGs,
    biu,
    damaturu,
    molai,
    yola,
    ajaokuta,
    gereguGs,
    gereguNipp,
    asaba,
    alaojiGs,
    owerri,
    ahaoda,
    transamadiGs,
    phMain,
    omokuGs,
    gbarainGs,
    riversIppGs,
    ugwuaji,
    newHaven,
    onitsha,
    okpaiGs,
    alaoji,
    aba,
    yenegoa,
    afamIv_vGs,
    afamViGs,
    itu,
    adiabor,
    eket,
    ibomGs,
    ikotAbasi,
    ikotEkpene,
    odukpaniGs
];
